brew 'asdf'
brew 'autossh'
brew 'bat'
brew 'cmake' # Neovim dependency
brew 'fd'
brew 'fish'
brew 'fswatch' # Neovim dependency
brew 'fzf'
brew 'gettext' # Neovim dependency
brew 'git-delta'
brew 'go'
brew 'gradle'
brew 'jq'
brew 'maven'
brew 'ninja' # Neovim dependency
brew 'node@18', link: true
brew 'pipx'
brew 'pre-commit'
brew 'pure'
brew 'ripgrep'
brew 'ruby'
brew 'rust'
brew 'tmux'
brew 'tmuxinator'
brew 'tree'
brew 'vim'
brew 'wget'
brew 'zsh'
brew 'zsh-autocomplete'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

if RUBY_PLATFORM =~ /darwin/
  cask 'font-hack-nerd-font'
  cask 'font-jetbrains-mono-nerd-font'
  cask 'font-mononoki-nerd-font'

  cask 'alt-tab'
  cask 'docker'
  cask 'hammerspoon'
  cask 'jordanbaird-ice'
  cask 'karabiner-elements'
  cask 'kitty'
  cask 'notunes'
  cask 'raycast'
  cask 'sf-symbols'
  cask 'wezterm-nightly'

  brew 'awscli'
  brew 'imagemagick'
end
