# ./.tmuxinator.yml

name: dotfiles
root: ~/dotfiles

windows:
  - editor:
  - nix:
      root: /etc/nix-darwin
  - custom:
      root: ~/dotfiles_custom
  - plugins:
      root: ~/.local/share/nvim/lazy
