"$schema" = 'https://starship.rs/config-schema.json'

format = """
$hostname\
$directory\
$shell\
$git_branch\
$git_status\
$git_state\
$cmd_duration\
$line_break\
$jobs\
$character"""

right_format = """
$bun\
$go\
$java\
$lua\
$nodejs\
$ruby\
$swift\
$time"""

[cmd_duration]
style = 'yellow'

[directory]
style = 'bold blue'
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[git_branch]
style = 'purple'
symbol = ' '

[git_status]
format = '[($all_status )](218)[($ahead_behind )](cyan)'
diverged = "⇡⇣"

[hostname]
ssh_symbol = ' '

[lua]
symbol = '󰢱 '

[shell]
format = 'on [$indicator]($style) '
disabled = false
style = 'green'

[time]
format = 'at [$time]($style)'
disabled = false
style = 'yellow'
