tap 'heroku/brew'
brew 'heroku'
brew 'openjdk@17', link: true

if RUBY_PLATFORM =~ /darwin/
  brew 'pam-reattach'

  cask 'dropbox'

  tap 'homebrew/cask-drivers'
  cask 'qmk-toolbox'
  cask 'zen-browser'
end
